const express = require("express");
const os = require("os");
const crypto = require("crypto");

const app = express();
const PORT = 3000;

app.use(express.json());
app.use(express.static("public"));

const urlStore = {};

// Root (frontend)
app.get("/health", (req, res) => {
  res.status(200).send("UP");
});

// API: shorten URL
app.post("/shorten", (req, res) => {
  const { url } = req.body;
  if (!url) return res.status(400).json({ error: "URL required" });

  const code = crypto.randomBytes(3).toString("hex");
  urlStore[code] = { url, clicks: 0 };

  res.json({
    shortUrl: `/${code}`,
    pod: os.hostname()
  });
});

// Redirect
app.get("/:code", (req, res) => {
  const entry = urlStore[req.params.code];
  if (!entry) return res.status(404).send("Not found");

  entry.clicks++;
  res.redirect(entry.url);
});

// Stats
app.get("/stats/all", (req, res) => {
  res.json({
    pod: os.hostname(),
    urls: urlStore
  });
});

// Load generator (HPA demo)
app.get("/load", (req, res) => {
  const start = Date.now();
  while (Date.now() - start < 300) {
    Math.sqrt(Math.random());
  }
  res.send(`Load generated by pod ${os.hostname()}`);
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
