const express = require("express");
const os = require("os");

const app = express();
const port = 3000;

app.get("/", (req, res) => {
  res.json({
    service: "cloud-autoscaling-webapp",
    pod: os.hostname(),
    status: "healthy"
  });
});

app.get("/health", (req, res) => {
  res.status(200).send("UP");
});

// CPU load generator
app.get("/load", (req, res) => {
  const start = Date.now();
  while (Date.now() - start < 300) {
    Math.sqrt(Math.random());
  }
  res.send(`Load generated by pod ${os.hostname()}`);
});

app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});
